export const CATS = ["Téléphones & HighTech","Mode & Accesoires","Alimentation","Maison & Decoration","Agricole","Beauté & Soins","BTP","Automobile","Éducation","Services"];

export const CITIES = ["Toutes les villes","Douala","Yaoundé","Bafoussam","Bamenda","Garoua","Kribi","Ngaoundéré","Maroua",,"Buea","Bertoua"];

export const ROLE_LABELS = { buyer:"🛍️ Acheteur", seller:"🏪 Vendeur", delivery:"🚚 Livreur", provider:"👷 Prestataire" };

export const DELIVERY_STATUSES = { pending:"⏳ En attente", en_cours:"🚚 En cours", livre:"✅ Livré", echec:"❌ Échoué" };

export const ESCROW_STATUSES = { pending:"⏳ En attente", securise:"🔐 Sécurisé", libere:"✅ Libéré", rembourse:"↩️ Remboursé" };

export const PREST_DATA = [
  {
    id: "p1",
    name: "Claude Mbassi",
    metier: "Plombier certifié",
    categorie: "Plomberie",
    ville: "Douala",
    quartier: "Akwa",
    emoji: "🔧",
    photo: "https://images.unsplash.com/photo-1620207418302-439b387441b0?w=400&q=80",
    color_bg: "linear-gradient(135deg, #dbeafe, #bfdbfe)",
    tags: ["Plomberie", "Sanitaire", "Chauffe-eau"],
    note: 4.9,
    avis: 87,
    prix: "15 000 FCFA/h",
    experience: "8 ans",
    verifie: true,
    top: true,
    dispo: true,
    bio: "Spécialiste en installations sanitaires et réparations d'urgence. Intervention rapide dans tout Douala. Devis gratuit.",
    telephone: "+237696565454",
    realisations: 340,
  },
  {
    id: "p2",
    name: "Électro Bertrand",
    metier: "Électricien",
    categorie: "Électricité",
    ville: "Yaoundé",
    quartier: "Bastos",
    emoji: "⚡",
    photo: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&q=80",
    color_bg: "linear-gradient(135deg, #fef3c7, #fde68a)",
    tags: ["Électricité", "Installation", "Dépannage"],
    note: 4.8,
    avis: 124,
    prix: "12 000 FCFA/h",
    experience: "12 ans",
    verifie: true,
    top: true,
    dispo: true,
    bio: "Installation électrique complète, mise aux normes, dépannage 24h/24. Travaux garantis 1 an.",
    telephone: "+237677884455",
    realisations: 450,
  },
  {
    id: "p3",
    name: "Raissa Design",
    metier: "Graphiste freelance",
    categorie: "Graphisme",
    ville: "Douala",
    quartier: "Bonanjo",
    emoji: "🎨",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    color_bg: "linear-gradient(135deg, #fce7f3, #fbcfe8)",
    tags: ["Logo", "Flyer", "Branding"],
    note: 5.0,
    avis: 56,
    prix: "25 000 FCFA/projet",
    experience: "5 ans",
    verifie: true,
    top: false,
    dispo: true,
    bio: "Création d'identité visuelle, logos, flyers et supports print. Style moderne et africain contemporain.",
    telephone: "+237699001122",
    realisations: 180,
  },
  {
    id: "p4",
    name: "PhotoCam Pro",
    metier: "Photographe",
    categorie: "Photographie",
    ville: "Kribi",
    quartier: "Centre-ville",
    emoji: "📸",
    photo: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=400&q=80",
    color_bg: "linear-gradient(135deg, #e0e7ff, #c7d2fe)",
    tags: ["Mariage", "Portrait", "Événementiel"],
    note: 4.9,
    avis: 203,
    prix: "50 000 FCFA/jour",
    experience: "10 ans",
    verifie: true,
    top: true,
    dispo: true,
    bio: "Photographe de mariage, portrait et événementiel. Studio équipé + déplacement partout au Cameroun.",
    telephone: "+237670223344",
    realisations: 520,
  },
  {
    id: "p5",
    name: "CleanPro237",
    metier: "Service de nettoyage",
    categorie: "Nettoyage",
    ville: "Douala",
    quartier: "Bonapriso",
    emoji: "🧹",
    photo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80",
    color_bg: "linear-gradient(135deg, #dcfce7, #bbf7d0)",
    tags: ["Ménage", "Bureaux", "Grand nettoyage"],
    note: 4.6,
    avis: 312,
    prix: "8 000 FCFA/h",
    experience: "6 ans",
    verifie: true,
    top: false,
    dispo: true,
    bio: "Nettoyage professionnel de maisons, bureaux et appartements. Produits écologiques. Équipe formée.",
    telephone: "+237655112233",
    realisations: 890,
  },
  {
    id: "p6",
    name: "DevCam Tech",
    metier: "Développeur Web",
    categorie: "Informatique",
    ville: "Yaoundé",
    quartier: "Nlongkak",
    emoji: "💻",
    photo: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&q=80",
    color_bg: "linear-gradient(135deg, #cffafe, #a5f3fc)",
    tags: ["Site web", "App", "E-commerce"],
    note: 4.8,
    avis: 41,
    prix: "200 000 FCFA/projet",
    experience: "7 ans",
    verifie: true,
    top: true,
    dispo: true,
    bio: "Création de sites web, applications mobiles et boutiques en ligne. Technologies React, Next.js, React Native.",
    telephone: "+237690112233",
    realisations: 95,
  },
  {
    id: "p7",
    name: "Kouakou Menuiserie",
    metier: "Menuisier ébéniste",
    categorie: "Menuiserie",
    ville: "Bafoussam",
    quartier: "Tamdja",
    emoji: "🪚",
    photo: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?w=400&q=80",
    color_bg: "linear-gradient(135deg, #fed7aa, #fdba74)",
    tags: ["Meubles", "Placards", "Sur-mesure"],
    note: 4.7,
    avis: 156,
    prix: "À partir de 50 000 FCFA",
    experience: "15 ans",
    verifie: true,
    top: false,
    dispo: true,
    bio: "Menuiserie traditionnelle et moderne. Fabrication de meubles sur-mesure, placards, portes et fenêtres.",
    telephone: "+237677445566",
    realisations: 420,
  },
  {
    id: "p8",
    name: "Chef Marguerite",
    metier: "Cuisinière événementielle",
    categorie: "Cuisine",
    ville: "Douala",
    quartier: "Logbessou",
    emoji: "👩‍🍳",
    photo: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400&q=80",
    color_bg: "linear-gradient(135deg, #fecaca, #fca5a5)",
    tags: ["Traiteur", "Mariages", "Cuisine locale"],
    note: 4.9,
    avis: 178,
    prix: "3 500 FCFA/pers.",
    experience: "20 ans",
    verifie: true,
    top: true,
    dispo: true,
    bio: "Traiteur spécialisé cuisine camerounaise et internationale. Ndolé, Poulet DG, Eru... pour mariages et événements.",
    telephone: "+237699778899",
    realisations: 260,
  },
  {
    id: "p9",
    name: "Beauté by Sandra",
    metier: "Coiffeuse à domicile",
    categorie: "Beauté",
    ville: "Yaoundé",
    quartier: "Mvan",
    emoji: "💇‍♀️",
    photo: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80",
    color_bg: "linear-gradient(135deg, #fbcfe8, #f9a8d4)",
    tags: ["Tresses", "Coloration", "Soins"],
    note: 5.0,
    avis: 89,
    prix: "10 000 FCFA/prest.",
    experience: "6 ans",
    verifie: true,
    top: false,
    dispo: true,
    bio: "Coiffure à domicile : tresses africaines, mèches, coloration, soins capillaires. Je me déplace partout à Yaoundé.",
    telephone: "+237651223344",
    realisations: 340,
  },
];

export const BLOG_DATA = [
  {
    id: 1,
    slug: "vendre-en-ligne-cameroun-2026",
    title: "Comment vendre en ligne au Cameroun en 2026 : le guide complet",
    excerpt: "Stratégies concrètes pour lancer ton business e-commerce au Cameroun : choix des produits, marketing WhatsApp, paiement mobile, logistique locale.",
    cat: "BUSINESS",
    emoji: "📈",
    color_bg: "linear-gradient(135deg, #dbeafe, #bfdbfe)",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    date: "15 avril 2026",
    read: "8 min",
    author: "Équipe Yorix",
    author_avatar: "Y",
    featured: true,
    external_url: "https://www.journalducameroun.com/e-commerce-au-cameroun-un-marche-en-pleine-expansion/",
    tags: ["E-commerce", "Cameroun", "Business"],
  },
  {
    id: 2,
    slug: "produits-camerounais-plus-vendus",
    title: "Les 10 produits camerounais les plus vendus en ligne",
    excerpt: "Beurre de karité, pagne wax, cacao, miel de Oku, poivre de Penja... Découvre les produits locaux qui cartonnent à l'international.",
    cat: "LOCAL",
    emoji: "🌿",
    color_bg: "linear-gradient(135deg, #dcfce7, #bbf7d0)",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    date: "12 avril 2026",
    read: "6 min",
    author: "Marie Tchoumi",
    author_avatar: "M",
    featured: false,
    external_url: "https://www.investiraucameroun.com/agriculture",
    tags: ["Produits locaux", "Export", "Artisanat"],
  },
  {
    id: 3,
    slug: "mtn-momo-vs-orange-money",
    title: "MTN MoMo vs Orange Money : quel système de paiement choisir ?",
    excerpt: "Comparatif détaillé des deux géants du mobile money au Cameroun : frais, limites, sécurité, intégration marchande et expérience utilisateur.",
    cat: "PAIEMENT",
    emoji: "💳",
    color_bg: "linear-gradient(135deg, #fef3c7, #fde68a)",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    date: "10 avril 2026",
    read: "7 min",
    author: "Jean-Paul Essomba",
    author_avatar: "J",
    featured: false,
    external_url: "https://www.gsma.com/mobilefordevelopment/mobile-money/",
    tags: ["MoMo", "Orange Money", "Fintech"],
  },
  {
    id: 4,
    slug: "suivi-commande-temps-reel",
    title: "Suivi de commande en temps réel : comment ça marche chez Yorix",
    excerpt: "Découvre notre système de tracking GPS inspiré d'Uber : de la collecte chez le vendeur jusqu'à ta porte, tu vois tout en direct.",
    cat: "LIVRAISON",
    emoji: "🚚",
    color_bg: "linear-gradient(135deg, #fed7aa, #fdba74)",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    date: "8 avril 2026",
    read: "5 min",
    author: "Équipe Yorix Ride",
    author_avatar: "R",
    featured: false,
    external_url: "https://www.uber.com/fr/newsroom/",
    tags: ["Livraison", "GPS", "Technologie"],
  },
  {
    id: 5,
    slug: "escrow-protection-acheteur",
    title: "Escrow Yorix : pourquoi ton argent est 100% protégé",
    excerpt: "Comprends en 5 minutes le système Escrow : ton paiement reste bloqué jusqu'à la livraison confirmée. Zéro arnaque, zéro stress.",
    cat: "SÉCURITÉ",
    emoji: "🔐",
    color_bg: "linear-gradient(135deg, #e9d5ff, #d8b4fe)",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80",
    date: "5 avril 2026",
    read: "4 min",
    author: "Équipe Sécurité",
    author_avatar: "S",
    featured: false,
    external_url: "https://en.wikipedia.org/wiki/Escrow",
    tags: ["Escrow", "Sécurité", "Paiement"],
  },
  {
    id: 6,
    slug: "electricien-fiable-douala",
    title: "Comment trouver un électricien fiable à Douala en 2026",
    excerpt: "Check-list complète : vérifier les qualifications, demander un devis, évaluer les avis, éviter les arnaques courantes dans le BTP camerounais.",
    cat: "PRESTATAIRES",
    emoji: "⚡",
    color_bg: "linear-gradient(135deg, #fecaca, #fca5a5)",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    date: "2 avril 2026",
    read: "6 min",
    author: "Service Prestataires",
    author_avatar: "P",
    featured: false,
    external_url: "https://www.cameroon-tribune.cm/",
    tags: ["BTP", "Douala", "Prestataires"],
  },
  {
    id: 7,
    slug: "pagne-wax-histoire-tendances",
    title: "Le pagne wax camerounais : histoire, tendances et où acheter",
    excerpt: "Du marché de Mokolo aux défilés internationaux, le pagne wax conquiert le monde. Guide complet pour reconnaître un vrai pagne de qualité.",
    cat: "MODE",
    emoji: "👗",
    color_bg: "linear-gradient(135deg, #fce7f3, #fbcfe8)",
    image: "https://images.unsplash.com/photo-1617627191894-1c9e59f7a4ab?w=800&q=80",
    date: "28 mars 2026",
    read: "9 min",
    author: "Fatima Abakar",
    author_avatar: "F",
    featured: false,
    external_url: "https://www.vogue.fr/mode/article/wax-pagne-africain-histoire",
    tags: ["Mode", "Pagne", "Culture"],
  },
  {
    id: 8,
    slug: "devenir-livreur-yorix",
    title: "Devenir livreur Yorix : gagne jusqu'à 150 000 FCFA/mois",
    excerpt: "Témoignages de livreurs actifs à Yaoundé et Douala, processus d'inscription, revenus réels et conseils pour maximiser tes gains.",
    cat: "CARRIÈRE",
    emoji: "🏍️",
    color_bg: "linear-gradient(135deg, #cffafe, #a5f3fc)",
    image: "https://images.unsplash.com/photo-1558383331-f520f2888351?w=800&q=80",
    date: "25 mars 2026",
    read: "7 min",
    author: "Équipe Yorix Ride",
    author_avatar: "R",
    featured: false,
    external_url: "https://www.cameroon-info.net/",
    tags: ["Emploi", "Livraison", "Revenus"],
  },
  {
    id: 9,
    slug: "fiscalite-vendeurs-cameroun",
    title: "Fiscalité des vendeurs en ligne au Cameroun : ce qu'il faut savoir",
    excerpt: "TVA, impôt sur le revenu, patente : toutes les obligations fiscales d'un e-commerçant camerounais expliquées simplement.",
    cat: "BUSINESS",
    emoji: "📊",
    color_bg: "linear-gradient(135deg, #dbeafe, #bfdbfe)",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    date: "22 mars 2026",
    read: "10 min",
    author: "Expert Comptable",
    author_avatar: "E",
    featured: false,
    external_url: "https://www.impots.cm/",
    tags: ["Fiscalité", "Impôts", "Business"],
  },
];

export const COURSES_DATA = [
  {emoji:"🏪",title:"Créer sa boutique en 1h",level:"Débutant",lc:"level-deb",duree:"1h30",apprenants:"2.4K",prix:"Gratuit",bg:"#e8f7ee"},
  {emoji:"📸",title:"Photographier ses produits",level:"Débutant",lc:"level-deb",duree:"2h",apprenants:"1.8K",prix:"Gratuit",bg:"#fff3e0"},
  {emoji:"📊",title:"Analyser ses ventes",level:"Intermédiaire",lc:"level-int",duree:"3h",apprenants:"920",prix:"5 000 FCFA",bg:"#e3f2fd"},
  {emoji:"💡",title:"Marketing digital Cameroun",level:"Intermédiaire",lc:"level-int",duree:"4h",apprenants:"640",prix:"8 000 FCFA",bg:"#fce4ec"},
  {emoji:"🤝",title:"Négocier avec les fournisseurs",level:"Avancé",lc:"level-adv",duree:"2h30",apprenants:"380",prix:"10 000 FCFA",bg:"#ede7f6"},
  {emoji:"🚀",title:"Scaler vers le B2B",level:"Avancé",lc:"level-adv",duree:"5h",apprenants:"210",prix:"15 000 FCFA",bg:"#e0f2f1"},
];

export const REWARDS_DATA = [
  {icon:"🎁",name:"Bon 5 000 FCFA",pts:500},
  {icon:"🚚",name:"Livraison gratuite x3",pts:300},
  {icon:"⭐",name:"Statut VIP Yorix",pts:1000},
  {icon:"📱",name:"-20% téléphones",pts:400},
  {icon:"☕",name:"Pack café 500g",pts:200},
  {icon:"🎓",name:"Cours Academy offert",pts:350},
];
