/**
 * Registre Lucide pour contenu (constants, pages marketing, livraison)
 */
import {
  ShoppingBag,
  Store,
  Truck,
  HardHat,
  Shield,
  ShieldCheck,
  Clock,
  CheckCircle2,
  XCircle,
  Bike,
  Package,
  Undo2,
  Wrench,
  Zap,
  Palette,
  Camera,
  Sparkles,
  Laptop,
  ChefHat,
  Scissors,
  TrendingUp,
  Leaf,
  CreditCard,
  Shirt,
  BarChart3,
  Gift,
  Star,
  Smartphone,
  Coffee,
  GraduationCap,
  Lightbulb,
  Handshake,
  Rocket,
  Globe,
  Target,
  MessageCircle,
  Building2,
  Gem,
  Flag,
  Search,
  MapPin,
  Briefcase,
  Megaphone,
  Building,
  Plane,
  Users,
  ShoppingCart,
  Hammer,
  CircleDot,
  DollarSign,
  Scale,
  Calendar,
  Phone,
  RefreshCw,
  X,
  UserCircle,
  AlertTriangle,
  PartyPopper,
  Lock,
  LifeBuoy,
  Tag,
  FileText,
  Clock3,
  Plus,
} from "lucide-react";

export const CONTENT_ICONS = {
  shoppingBag: ShoppingBag,
  store: Store,
  truck: Truck,
  hardHat: HardHat,
  shield: Shield,
  shieldCheck: ShieldCheck,
  clock: Clock,
  check: CheckCircle2,
  x: XCircle,
  bike: Bike,
  package: Package,
  undo: Undo2,
  wrench: Wrench,
  zap: Zap,
  palette: Palette,
  camera: Camera,
  sparkles: Sparkles,
  laptop: Laptop,
  chefHat: ChefHat,
  scissors: Scissors,
  trendingUp: TrendingUp,
  leaf: Leaf,
  creditCard: CreditCard,
  shirt: Shirt,
  barChart: BarChart3,
  gift: Gift,
  star: Star,
  smartphone: Smartphone,
  coffee: Coffee,
  graduationCap: GraduationCap,
  lightbulb: Lightbulb,
  handshake: Handshake,
  rocket: Rocket,
  globe: Globe,
  target: Target,
  messageCircle: MessageCircle,
  building2: Building2,
  gem: Gem,
  flag: Flag,
  search: Search,
  mapPin: MapPin,
  briefcase: Briefcase,
  megaphone: Megaphone,
  building: Building,
  plane: Plane,
  users: Users,
  shoppingCart: ShoppingCart,
  hammer: Hammer,
  circleDot: CircleDot,
  dollarSign: DollarSign,
  scale: Scale,
  calendar: Calendar,
  phone: Phone,
  refresh: RefreshCw,
  close: X,
  userCircle: UserCircle,
  alert: AlertTriangle,
  partyPopper: PartyPopper,
  lock: Lock,
  lifeBuoy: LifeBuoy,
  tag: Tag,
  fileText: FileText,
  clock3: Clock3,
  plus: Plus,
};

export const DELIVERY_STATUS_ICONS = {
  commande_recue: Clock,
  livreur_assigne: Bike,
  accepte: CheckCircle2,
  refuse: XCircle,
  preparation: Package,
  collecte: Store,
  en_route: Bike,
  livre: CheckCircle2,
  annule: XCircle,
};

export const ROLE_ICON_KEYS = {
  buyer: "shoppingBag",
  seller: "store",
  delivery: "truck",
  provider: "hardHat",
  admin: "shield",
  admin_partner: "handshake",
  superadmin: "shieldCheck",
};

export const PREST_CATEGORY_ICON_KEYS = {
  Plomberie: "wrench",
  Électricité: "zap",
  Graphisme: "palette",
  Photographie: "camera",
  Nettoyage: "sparkles",
  Informatique: "laptop",
  Menuiserie: "hammer",
  Cuisine: "chefHat",
  Beauté: "scissors",
  Transport: "truck",
  Couture: "scissors",
  Réparation: "hammer",
};

export function ContentIcon({ name, size = 18, className = "", strokeWidth = 2.25, ...props }) {
  const Icon = CONTENT_ICONS[name];
  if (!Icon) return null;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...props} />;
}

export function DeliveryStatusIcon({ statut, size = 16, className = "" }) {
  const Icon = DELIVERY_STATUS_ICONS[statut];
  if (!Icon) return <CircleDot size={size} className={className} aria-hidden="true" />;
  return <Icon size={size} strokeWidth={2.25} className={className} aria-hidden="true" />;
}

export function prestIconKey(prest) {
  if (prest?.iconKey) return prest.iconKey;
  if (prest?.categorie) return PREST_CATEGORY_ICON_KEYS[prest.categorie] || "hardHat";
  return "hardHat";
}
