/** Colonnes catalogue (grille + recherche) — évite SELECT * sur les listes produits. */
export const PRODUCT_LIST_COLUMNS = [
  "id",
  "name_fr",
  "description_fr",
  "prix",
  "stock",
  "categorie",
  "category_id",
  "image",
  "image_urls",
  "ville",
  "vendeur_nom",
  "vendeur_id",
  "note",
  "nombre_avis",
  "vues",
  "sponsorise",
  "flash",
  "escrow",
  "vente_total",
  "promo",
  "promo_pct",
  "promo_starts_at",
  "promo_ends_at",
  "has_variants",
  "variants",
  "is_made_in_cameroon",
  "made_in_cameroon_status",
  "actif",
  "b2b_enabled",
  "prix_gros",
  "min_qty_gros",
  "country_of_origin",
  "country_of_origin_other",
  "lead_time_days",
  "incoterm",
  "wholesale_tiers",
  "vendeur_verifie",
  "created_at",
].join(",");

export const GLOBAL_PRODUCTS_LIMIT = 120;
